[options]
addons_path = addons
db_host = localhost
db_port = 5432
db_user = odoo_user
db_password = odoo_pass
db_name = odoodb
admin_passwd = $pbkdf2-sha512$600000$RMg5p1TqXQsBYIxRai3FmA$IQ7YeR7KakGZyBA79vHKOZUUvd/RYLrv79szamcW8SGVuMzKE2QkQGmVJzlOQ6c7glXqEbVLmV5F.HX8TyeDqQ

